### PR TITLE
Namespace update to `Adapters`

### LINKED ISSUE #82: Namespace update to `Adapters`
#### Broken rules:

Following confirmation [here](https://github.com/BHoM/BHoM_Adapter/issues/213#issuecomment-631687011) the namespace in this toolkit, for all items except the adapter should have the namespace `BH.oM.Adapters.Radiance` or `BH.Engine.Adapters.Radiance` instead of `BH.oM.Radiance`, etc.

The Adapter namespace should remain at `BH.Adapter.Radiance` instead of `BH.Adapter.External.Radiance`.

#### Suggestions to restore compliance:

As above.

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #82 

See issue for details

### CODE REVIEW

**Review by FraserGreenroyd — APPROVED** [review]
All the checks have passed so happy with this PR, dependants look ok too.

**Review by pawelbaran — APPROVED** [review]
LGTM

**Review by alelom — APPROVED** [review]
LGTM!

**Pull request merged**
