### PR TITLE
Upgrade to Mongo version 2.18

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes [#](https://github.com/BHoM/BHoM_Engine/issues/2948)

### CODE REVIEW

**Comment by adecler** [comment]
@BHoMBot check compliance

**Review by FraserGreenroyd — APPROVED** [review]
See [this review](https://github.com/BHoM/BHoM_Engine/pull/2949#pullrequestreview-1189928294)

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check  ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
