### PR TITLE
Update Assembly Version

### PR DESCRIPTION
**Pull request by BHoMBot**
Updates Assembly Version to 4.3

### CODE REVIEW

**Review by FraserGreenroyd — APPROVED** [review]
Approved from a CI/CD perspective.

**Comment by adecler** [comment]
@BHoMBot check required

**Comment by adecler** [comment]
@FraserGreenroyd , are those outdated checks ?

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check core
@BHoMBot check versioning
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 3112935457

**Comment by FraserGreenroyd** [comment]
> @FraserGreenroyd , are those outdated checks ?

They were, they've now been updated 👍

**Pull request merged**
