### PR TITLE
Upgrade to .NetStandard2.0

### LINKED ISSUE #115: Upgrade to .NetStandard2.0
In line with other toolkits close to the core.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #115

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 12058730980

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Review by adecler — APPROVED** [review]
Still compiles and copies the dlls across. 
Tested on a few sample scripts and still works as expected.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
